return {
    type = "document",
    has_doctype = true,
    name = "html",
    system_identifier = "",
    public_identifier = "",
    quirks_mode = "no-quirks",
    {
        type = "comment",
        text = " document.root isn't always document[1] ",
        line = 2,
        column = 1,
        offset = 16,
    },
    {
        type = "element",
        tag = "html",
        line = 3,
        column = 1,
        offset = 64,
        parse_flags = {
            implicit_end_tag = true,
            insertion_implied = true,
            insertion_by_parser = true,
        },
        {
            type = "element",
            tag = "head",
            line = 3,
            column = 1,
            offset = 64,
            parse_flags = {
                implicit_end_tag = true,
                insertion_implied = true,
                insertion_by_parser = true,
            },
            {
                type = "element",
                tag = "title",
                line = 3,
                column = 1,
                offset = 64,
                {
                    type = "text",
                    text = "Test Document",
                    line = 3,
                    column = 8,
                    offset = 71,
                },
            },
            {
                type = "whitespace",
                text = "\n",
                line = 3,
                column = 29,
                offset = 92,
            },
        },
        {
            type = "element",
            tag = "body",
            line = 4,
            column = 1,
            offset = 93,
            parse_flags = {
                implicit_end_tag = true,
                insertion_implied = true,
                insertion_by_parser = true,
            },
            {
                type = "element",
                tag = "h1",
                line = 4,
                column = 1,
                offset = 93,
                {
                    type = "text",
                    text = "Test Heading",
                    line = 4,
                    column = 5,
                    offset = 97,
                },
            },
            {
                type = "whitespace",
                text = "\n",
                line = 4,
                column = 22,
                offset = 114,
            },
            {
                type = "element",
                tag = "p",
                line = 5,
                column = 1,
                offset = 115,
                {
                    type = "element",
                    tag = "a",
                    line = 5,
                    column = 4,
                    offset = 118,
                    attr = {
                        href = "foobar.html",
                    },
                    {
                        type = "text",
                        text = "Quux",
                        line = 5,
                        column = 24,
                        offset = 138,
                    },
                },
            },
            {
                type = "whitespace",
                text = "\n",
                line = 5,
                column = 36,
                offset = 150,
            },
            {
                type = "element",
                tag = "iNValID",
                line = 6,
                column = 1,
                offset = 151,
                attr = {
                    foo = "bar",
                },
                {
                    type = "text",
                    text = "abc",
                    line = 6,
                    column = 20,
                    offset = 170,
                },
            },
            {
                type = "whitespace",
                text = "\n\t",
                line = 6,
                column = 33,
                offset = 183,
            },
            {
                type = "element",
                tag = "p",
                line = 7,
                column = 8,
                offset = 185,
                attr = {
                    class = "empty",
                },
            },
            {
                type = "whitespace",
                text = "\n",
                line = 7,
                column = 27,
                offset = 204,
            },
            {
                type = "comment",
                text = " comment node ",
                line = 8,
                column = 1,
                offset = 205,
            },
            {
                type = "whitespace",
                text = "\n",
                line = 8,
                column = 22,
                offset = 226,
            },
        },
    },
}
