#!/usr/bin/env lua
-- Prevent over-length commit messages

local COMMIT_EDITMSG = assert(arg[1])
local i = 0

local function fail(...)
    io.stderr:write("Error: ", string.format(...))
    os.exit(1)
end

for line in io.lines(COMMIT_EDITMSG) do
    i = i + 1
    if line:sub(1, 1) ~= "#" and line:len() > 72 then
        fail("line %d of commit message exceeds 72 columns\n", i)
    end
end
